### ISSUE TITLE
del 2.2.0

### ISSUE THREAD

**Issue by lmjohansen** [frontend-tooling/sample-project-gulp#2]
Hi, 
Having trouble following examples in chapter 3.. 
Took branch ch4 - package.json "del": "^2.0.1" installs 2.2.0

So this don't work anymore: 
gulp.task('clean', function(done) {
     del(['dist']).then(done);
});

should be:
gulp.task('clean', function(done) {
     del(['dist']).then(path=>{
          done();
     });
});

**Comment by ddprrt** [comment]
Hi Lars!

Oh boy, thank you for mentioning it. It should actually be

``` javascript
gulp.task('clean', function (done) {
  return del(['dist']);
});
```

`del` returns a Promise since version 2, and this is totally compatible with the task system. Your approach works too. I submitted this change to the publisher already. Will make sure this is published in the MEAP.

Thank you for noticing!

**Comment by jeggett** [comment]
What's the point to provide anonymous function with callback "done", if we never call it from within the function?

**Comment by ddprrt** [comment]
@jeggett you are right. The done callback's pretty useless.
@lmjohansen This has been fixed in the upcoming chapters. Thanks again fro noticing!
